### ISSUE TITLE
Dependencies problem

### ISSUE THREAD

**Issue by mociepka** [activefrequency/pyavatax#10]
I have problem with fixed dependencies versions, especially with `six`. Could the pyavatax uses `>=` instead `==` statement? That will solve my first issue with dependencies.

Second problem I have with `distutils`. In my project almost all packages uses `setuptools` and my package uses it too. Mixing `setuptools` with `distutils` causes versions conflict even with `>=` statement.

`Setuptools` is [recommended way](https://python-packaging-user-guide.readthedocs.org/en/latest/current/) of packages creation could the pyavatax uses it?

**Comment by jobelenus** [comment]
I'm going to merge your pull-request for `setuptools` over `distutils`. What is the specific issue you're having with `six`? Is it reproducible?

**Comment by mociepka** [comment]
With current version try `./setup develop` with:

```python
#! /usr/bin/env python
from setuptools import setup, find_packages

setup(
    name='test',
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        'Babel==1.3',
        'BabelDjango==0.2.2',
        'Celery==3.1.19',
        'Django==1.8.5',
        'django-emailit==0.2.2',
        'django-mailgun==0.8.0',
        'django-materializecss-form==0.0.64',
        'django-model-utils==2.0.3',
        'django-mptt==0.7.4',
        'django-payments==0.8.0',
        'django-prices==0.4.1',
        'django-redis-cache==1.6.4',
        'djangorestframework==3.1.3',
        'django-selectable==0.8.0',
        'django-versatileimagefield==1.0.6',
        'eventlet==0.17.4',
        'Fabric==1.10.2',
        'fake-factory==0.5.3',
        'google-measurement-protocol==0.1.4',
        'Jinja2==2.8',
        'jsonfield==1.0.3',
        'Markdown==2.6.2',
        'msgpack-python==0.4.6',
        'prices==0.5.4',
        'psycopg2==2.6.1',
        'PyAvaTax==1.3.4',
        'requests==2.5.3',
        'retrying==1.3.3',
        'satchless==1.1.3',
        'Unidecode==0.04.18',
        'uWSGI==2.0.11.2'
    ]
)
```

**Comment by jobelenus** [comment]
I've merged your pull request, however, I've kept the versions of the libraries pinned because I don't want future upgrades in any libraries to get automatically installed and break functionality. 

I created another setup script with your example, and running `develop` gave me this error:
`Error: pg_config executable not found.`

`pg_config` is found in `postgresql-devel`, which (on Ubuntu at least) can be installed with `sudo apt-get install libpq-dev`

Please do let me know if that solves your problem. Or if there is a different problem and Pyavatax needs to upgrade versions of libraries.

**Comment by jobelenus** [comment]
I have locally upgraded the three required libraries to their newest versions (requests 2.8.1, decorator 4.0.4, and six 1.10.0) and ran the test library with no failures.

**Comment by jobelenus** [comment]
I've made a change to setup install requires to give a range of versions where the library is known to work for requests. The other two are safe.

**Comment by mociepka** [comment]
:+1: please don't forget to release new version to the `pypi`.

**Comment by jobelenus** [comment]
I will once all your issues are sorted out. I don't want to make a million
releases

**Comment by mociepka** [comment]
I added archive zip to `dependency_links` in setup and everything works fine for me.
