### ISSUE TITLE
Adhere PyAvatax to the new Django 1.9 app_label policy

### ISSUE THREAD

**Issue by alvarocavalcanti** [activefrequency/pyavatax#12]
### Description
I want to be able to use pyavatax on a Django 1.9 project, migrating from versions 1.7 and 1.8.

### Details
Django's version 1.9 requires the modules to either define an `app_label` or to be added to the `INSTALLED_APPS` dictionary.

Here follows the console error:
`RuntimeError: Model class pyavatax.models.AvaTaxRecord doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.`

**Comment by jobelenus** [comment]
Hi Alvaro,

My understanding (and I could be very wrong) of this RuntimeError in Django
1.9 is that if `pyavatax` is in your applications INSTALLED_APPS directory,
everything will be fine. Is it there? Or is it not there on purpose for a
specific reason?

On Tue, Jan 19, 2016 at 1:42 PM, Alvaro Cavalcanti <notifications@github.com

**Comment by alvarocavalcanti** [comment]
Hi John,

This INSTALLED_APPS isn't a directory really, it's a dictionary defined in Django's base.py configuration file. We're using pyavatax as an external library, installed via `pip`. I have added it to the aforementioned dictionary and the error is gone.

My suggestion would be for you guys to have an `app_label` declared within your base package as this wouldn't require your users to change any code other than upgrading pyavatax. But that's up to you guys. :)

**Comment by jobelenus** [comment]
Pardon me, yes dictionary, not directory. We do want to make sure that when Django users use this package they do add it to INSTALLED_APPS because that guarantees several things happening that the package would rely on. Thanks!

**Comment by alvarocavalcanti** [comment]
Alright! :)

Em qua, 20 de jan de 2016 às 15:50, John Obelenus <notifications@github.com>
escreveu:
