### ISSUE TITLE
Require Django?

### ISSUE THREAD

**Issue by jeffreyfuchang** [activefrequency/pyavatax#13]
Docs say don't require django but trying without django installed yields the below. So yes I need django? Thanks.

Tried:
```from pyavatax import api as pyavatax_api```

Got:
```python2.7/site-packages/pyavatax/django_integration.py in <module>()
----> 1 from django.utils import timezone
      2 
      3 
      4 class MockDjangoRecorder(object):
      5 

ImportError: No module named django.utils
```

**Comment by kgrinberg** [comment]
It's a regression introduced in #11. Should be able to fix this and get a new release out this week.
