### ISSUE TITLE
403 errors from Avalara validating address

### ISSUE THREAD

**Issue by LiteWait** [activefrequency/pyavatax#14]
This code has been working for 2 years, but seems Avalara changed something in their APIs.  Since the _request method (whether you are providing a GET or POST) always adds a request body (aka: 'data') this causes Avalara to throw a 403 error on GETs.  Simple fix is to not provide 'data' on get.

  ```
 def _request(self, http_method, stem, data={}, params={}):
        url = '%s/%s' % (self.url, stem)
        data = json.dumps(data)
        # getting rid of control characters
        # that JSON will error out on
        data = data.replace('\\r', ' ')
        data = data.replace('\\t', ' ')
        data = data.replace('\\n', ' ')
        kwargs = {
            'params': params,
            'data': data,    REMOVE THIS AND THE 403 GOES AWAY
            'headers': self.headers,
            'auth': (self.username, self.password),
            'proxies': self.proxies,
            'timeout': self.timeout
        }
```

Please advise.

**Comment by jobelenus** [comment]
LiteWait, generally HTTP 403 responses are because of bad permissions/lack of permissions at the URI. Can you share an actual request with `params` where its giving you a 403 so I can confirm the problem?

**Comment by LiteWait** [comment]
Simple example demonstrating the problem.  I mimic'd the code from base.py
_request() method that gets a 403 as well.  This code should give you a
403, till you comment out the empty json object in the request body.

import requests
url = 'https://development.avalara.net/1.0/address/validate'
kwargs = {
    'headers': None,
    'params': {
        'PostalCode': '78746-5150',
        'Region': 'TX',
        'City': 'Austin',
        'Line1': '700 Las Cimas Parkway',
        'Country': 'US',
        'Line2': ''},
    'data': '{}',  # Remove this, it works. Avalara must be freaking on
HTTP GET with request body now!
    'auth': ('XXXXXXXXXX', 'XXXXXXXXXXXXXXXX'),
    'timeout': 10.0,
    'proxies': {}
}
resp = requests.get(url, **kwargs)
print('RESPONSE {0}:\n{1}'.format(resp.status_code, resp.text))

**Comment by jobelenus** [comment]
OK, I can confirm. Will put out a fix in a minute

**Comment by jobelenus** [comment]
New release and tag, 1.3.9.

**Comment by LiteWait** [comment]
Looks good. Thanks.
