### ISSUE TITLE
get_tax and lat/long requirements

### ISSUE THREAD

**Issue by ferringb** [activefrequency/pyavatax#6]
Looks of it, the lat/long parameters to get_tax are fairly specific- they're not needed (nor necessarily known as best I can tell) for most get tax requests.

With that in mind, I'd normally just submit a PR that makes them optional- the problem is that the signature is `def get(self, lat, lng, doc, sales_amount=None):` ... Which makes it an API breaking change.

What's the best way to clean up that api?  Adding a get_tax2 is a bit ugly, but seems like the way forward imo if you want to preserve API compatibility.

**Comment by jobelenus** [comment]
Ah, I think there is some miscommunication going on. It seems that Avalara has vastly improved their documentation and changed how they reference some things. This `get_tax` call that you see implemented here is actually what Avalara is calling the `EstimateTax` function ( [see here](http://developer.avalara.com/wp-content/apireference/master/?php#estimatetax) ). So I can't actually remove the lat/long pair as they actually generate the URL where we are making the request.
