### ISSUE TITLE
Dependencies problem

### ISSUE THREAD

**Issue by mociepka** [activefrequency/pyavatax#8]
PyAvaTax is importing main package for version number in setup.py script. But main script requires dependencies from setup.py.

**Comment by jobelenus** [comment]
None of the pyavatax code/modules uses setup.py (nor should it ever).
Setup.py is outside the module and is only used for PYPI distribution.

**Comment by mociepka** [comment]
I haven't explained issue well. Problem is in the `setup.py` file. Your versioning strategy causes imports problem.

You import `pyavatax` in `setup.py` before installation `__import__('pyavatax').get_version()`. But `pyavatax/__init__.py` imports `api` module and it try imports `decorator` module but it is not installed yet. 

Please read [python packages versioning guide](http://python-packaging-user-guide.readthedocs.org/en/latest/single_source_version/) point 6. I suggest create separate `version.py` file with `__version__` variable without any imports. It can be used in package and in `setup.py` file.

**Comment by jobelenus** [comment]
Oh, I think you're misunderstanding the purpose of the setup file. It's not
an installation file. It's only run by the maintainers to deploy a new
version to pypi. If you were to run it you wouldn't have credentials and it
would fail. You don't need to worry about this file

**Comment by jobelenus** [comment]
Sorry, now I understand what you're trying to do with setup.py.

**Comment by jobelenus** [comment]
1.3.4 takes care of this. Thank you!
